### PR TITLE
Feature ui

### PR DESCRIPTION
**Pull request by Eanilsen**
Feature-ui represents the most feature packed version of the program. I suggest a merge into develop for the purpose of updating the dev-branch.

### CODE REVIEW

**Comment by simenfuglestad** [comment]
I agree, feature-ui has essentially become develop which is not a good thing.

**Comment by jondam93** [comment]
Go for it

**Comment by Jeyloh** [comment]
Yes, this is great. In my modules of the software, 'game' and 'host' screens, there are no bugs. There is lacking UI but they are just cosmetic and will not hinder development on any other modules. Go for it.

**Comment by Jorghg** [comment]
Sounds like we are in agreement ! Updating develop with the UI feature will be a good step in improving the program and showcase the work that has been put in the project .

**Pull request merged**
